job:
  include:
    - arch: amd64
      env: TYPE=VM
    - arch: ppc64le
      env: TYPE=LXD
    - arch: s390x
      env: TYPE=LXD
    - arch: arm64
      env: TYPE=LXD

services:
  - docker

script:
  - sudo cat /etc/docker/daemon.json
