job:
  include:
    - arch: amd64
      env: TYPE=VM
    - arch: ppc64le
      env: TYPE=LXD
    - arch: s390x
      env: TYPE=LXD
    - arch: arm64
      env: TYPE=LXD
    - os: linux-ppc64le
      env: TYPE=VM

services:
  - docker

script:
  - arch
  - docker run -t ubuntu:18.04 bash -c 'ls -l /'
  - docker run --privileged -t ubuntu:18.04 bash -c 'ls -l /'
  - docker ps -a
