arch: 
  - ppc64le
  - s390x
  - arm64
  
services:
  - docker

script:
  - ls -l /
  - docker run -t ubuntu:18.04 bash -c 'ls -l /'
  - docker run --privileged -t ubuntu:18.04 bash -c 'ls -l /'
  - docker ps -a
